### ISSUE TITLE
Fehlende Fonts

### ISSUE THREAD

**Issue by SquallHalle** [entropia/gpn17-badge-ui#3]
Hey,

`#include <Fonts/FreeSans24pt7b.h>`
`#include <Fonts/FreeSans9pt7b.h>`
`#include <Fonts/FreeSans7pt7b.h>`
`#include <Fonts/Org_01.h>`

aber leider nur FreeSans7pt7b.h im /src/Fonts/

**Comment by Jana-Marie** [comment]
FreeSans7pt7b ist die einzige Font die nicht existiert
https://github.com/entropia/Adafruit-GFX-Library/tree/master/Fonts
